name: 8.6 Generate Token Wrong Credentials
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: GenerateToken
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: "123456"
        cxSkipIfFail: true
        cxVersion: "8.6"
