name: 'Checkmarx Scan'
description: 'Find vulnerabilities in your code using Checkmarx SAST solution'
author: 'Miguel Freitas'
inputs:
  cxServer:
    description: 'IP address or resolvable name of CxSAST web server.'
    required: true
    default: 'https://company.checkmarx.com'
runs:
  using: 'node12'
  image: 'index.js'
branding:
  icon: 'check'
  color: 'green'