name: 'Checkmarx Scan'
description: 'Find vulnerabilities in your code using Checkmarx SAST solution'
author: 'Miguel Freitas'
inputs:
  cxServer:
    description: 'IP address or resolvable name of CxSAST web server.'
    required: true
    default: 'https://company.checkmarx.com'
  cxUsername:
    description: 'Checkmarx Username'
    required: true
    default: 'first.last@company.com'
  cxPassword:
    description: 'Checkmarx Password'
    required: true
    default: '*********'
  cxTeam:
    description: 'Checkmarx Team'
    required: true
    default: '\CxServer\SP\Company'
  cxPreset:
    description: 'If not provided, will use preset defined in existing project or, for a new project, the default preset.'
    required: false
    default: 'Checkmarx Default'
  cxHigh:
    description: 'Threshold for High Severity Vulnerabilities'
    required: false
    default: -1
  cxMedium:
    description: 'Threshold for Medium Severity Vulnerabilities'
    required: false
    default: -1
  cxLow:
    description: 'Threshold for Low Severity Vulnerabilities'
    required: false
    default: -1
  cxComment:
    description: 'Saves a comment with the scan results. For example -comment important scan1.'
    required: false
    default: '_'
runs:
  using: 'node12'
  image: 'index.js'
branding:
  icon: 'check'
  color: 'green'