name: 'Checkmarx Scan'
description: 'Find vulnerabilities in your code using Checkmarx SAST solution'
author: 'Miguel Freitas'
inputs:
  cxAction:
    description: 'Checkmarx CLI Action'
    required: false
    default: 'Scan'
  cxVersion:
    description: 'Checkmarx Version'
    required: false
    default: '8.9'
  cxServer:
    description: 'IP address or resolvable name of CxSAST web server.'
    required: true
    default: 'https://company.checkmarx.com'
  cxUsername:
    description: 'Checkmarx Username'
    required: true
    default: 'first.last@company.com'
  cxToken:
    description: 'Checkmarx Token'
    required: false
    default: ''
  cxPassword:
    description: 'Checkmarx Password'
    required: true
    default: ''
  cxTeam:
    description: 'Checkmarx Team'
    required: true
    default: ''
  cxProject:
    description: 'Checkmarx Project Name'
    required: false
    default: ''
  cxPreset:
    description: 'If not provided, will use preset defined in existing project or, for a new project, the default preset.'
    required: false
    default: 'Checkmarx Default'
  cxHigh:
    description: 'Threshold for High Severity Vulnerabilities'
    required: false
    default: -1
  cxMedium:
    description: 'Threshold for Medium Severity Vulnerabilities'
    required: false
    default: -1
  cxLow:
    description: 'Threshold for Low Severity Vulnerabilities'
    required: false
    default: -1
  cxComment:
    description: 'Saves a comment with the scan results. For example -comment important scan1.'
    required: false
    default: ''
  cxForceScan:
    description: 'Force scan on source code, which has not been changed since the last scan of the same project. (Not compatible with -Incremental option.)'
    required: false
    default: false
  cxIncremental:
    description: 'Run incremental scan instead of a full scan.'
    required: false
    default: false
  cxExcludeFolders:
    description: 'Comma separated list of folder name patterns to exclude from scan. For example, exclude all test and log folders: -locationPathExclude test*,log_*'
    required: false
    default: ''
  cxExcludeFiles:
    description: 'Comma separated list of file name patterns to exclude from scan. For example, exclude all files with .class extension: -locationFilesExclude *.class'
    required: false
    default: ''
  cxConfiguration:
    description: 'Code language configuration. Possible values are : Default Configuration, Japanese (Shift-JIS). If configuration is not set, Default Configuration is used.'
    required: false
    default: 'Default Configuration'
  cxPrivate:
    description: 'Scan will not be visible to other users.'
    required: false
    default: false
  cxLog:
    description: 'Log file to be created.'
    required: false
    default: ''
  cxVerbose:
    description: 'Turns on verbose mode. All messages and events will be sent to the console or log file.'
    required: false
    default: true
  cxOsaHigh:
    description: 'OSA high severity vulnerability threshold. If the number of high vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).'
    required: false
    default: -1
  cxOsaMedium:
    description: 'OSA medium severity vulnerability threshold. If the number of medium vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).'
    required: false
    default: -1
  cxOsaLow:
    description: 'OSA low severity vulnerability threshold. If the number of high vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).'
    required: false
    default: -1
  cxOsaLocationPath:
    description: 'Local or network path to sources or source repository branch. May include multiple list of folders (local or shared) separated by comma.'
    required: false
    default: ''
  cxOsaArchiveToExtract:
    description: 'Comma separated list of file extensions to extract in the OSA scan.
    For example: -OsaArchiveToExtract *.zip extracts only files with .zip extension.'
    required: false
    default: ''
  cxOsaFilesInclude:
    description: 'Comma separated list of file name patterns to exclude from the OSA scan. 
    For example: *.dll will include only dll files.'
    required: false
    default: ''
  cxOsaFilesExclude:
    description: 'Comma separated list of file name patterns to exclude from the OSA scan. 
    Exclude extensions by using *.<extension>, or exclude files by using */<file>.
    Examples: -OsaFilesExclude *.class excludes all files which start with the .class.
    Examples: -OsaFilesExclude */plexus-utils-1.5.6.jar excludes all files which start with plexus-utils-1.5.6.jar.'
    required: false
    default: ''
  cxOsaPathExclude:
    description: 'Comma separated list of folder path patterns to exclude from the OSA scan. 
    For example: -OsaPathExclude test excludes all folders which start with test prefix.'
    required: false
    default: ''
  cxOsaReportHtml:
    description: 'Generate CxOSA HTML report.'
    required: false
    default: ''
  cxOsaReportPDF:
    description: 'Generate CxOSA PDF report.'
    required: false
    default: ''
  cxOsaDepth:
    description: 'Extraction depth of files to include in the OSA scan.'
    required: false
    default: ''
  cxExecutePackageDependency:
    description: 'Retrieve all supported package dependencies before performing OSA scan (see Remarks section).'
    required: false
    default: false
  cxOsaJson:
    description: 'Generate CxOSA JSON report.'
    required: false
    default: ''
  cxCheckPolicy:
    description: 'This parameter will break the build if the CxOSA policy is violated.'
    required: false
    default: false
  cxSkipIfFail:
    description: 'Skip Checkmarx Action Step if Fail'
    required: false
    default: false
  cxTrustedCertificates:
    description: 'Trust Self-signed Certificates'
    required: false
    default: false
  cxGithubToken:
    description: 'Github Token Secret'
    required: false
    default: ''
  cxGithubIssues:
    description: 'Create Github Issues'
    required: false
    default: false
  cxGithubLabels:
    description: 'Github Labels for Issues created'
    required: false
    default: 'bug'
  cxGithubAssignees:
    description: 'Github Assignees for Issues created'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'src/index.js'
branding:
  icon: 'check'
  color: 'green'