name: 'Checkmarx Scan'
description: 'Find vulnerabilities in your code using Checkmarx SAST solution'
author: 'Miguel Freitas'
inputs:
  cxServer:
    description: 'IP address or resolvable name of CxSAST web server.'
    required: true
    default: 'https://company.checkmarx.com'
  cxUsername:
    description: 'Checkmarx Username'
    required: true
    default: 'first.last@company.com'
  cxPassword:
    description: 'Checkmarx Password'
    required: true
    default: '*********'
  cxTeam:
    description: 'Checkmarx Team'
    required: true
    default: ''
  cxPreset:
    description: 'If not provided, will use preset defined in existing project or, for a new project, the default preset.'
    required: false
    default: 'Checkmarx Default'
  cxHigh:
    description: 'Threshold for High Severity Vulnerabilities'
    required: false
    default: -1
  cxMedium:
    description: 'Threshold for Medium Severity Vulnerabilities'
    required: false
    default: -1
  cxLow:
    description: 'Threshold for Low Severity Vulnerabilities'
    required: false
    default: -1
  cxComment:
    description: 'Saves a comment with the scan results. For example -comment important scan1.'
    required: false
    default: ''
  cxForceScan:
    description: 'Force scan on source code, which has not been changed since the last scan of the same project. (Not compatible with -Incremental option.)'
    required: false
    default: false
  cxIncremental:
    description: 'Run incremental scan instead of a full scan.'
    required: false
    default: false
  cxExcludeFolders:
    description: 'Comma separated list of folder name patterns to exclude from scan. For example, exclude all test and log folders: -locationPathExclude test*,log_*'
    required: false
    default: ''
  cxExcludeFiles:
    description: 'Comma separated list of file name patterns to exclude from scan. For example, exclude all files with .class extension: -locationFilesExclude *.class'
    required: false
    default: ''
  cxConfiguration:
    description: 'Code language configuration. Possible values are : Default Configuration, Japanese (Shift-JIS). If configuration is not set, Default Configuration is used.'
    required: false
    default: 'Default Configuration'
  cxPrivate:
    description: 'Scan will not be visible to other users.'
    required: false
    default: false
  cxLog:
    description: 'Log file to be created.'
    required: false
    default: ''
  cxVerbose:
    description: 'Turns on verbose mode. All messages and events will be sent to the console or log file.'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'check'
  color: 'green'