name: 2020.2.11 SAST Scan
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxAction: Scan
        cxServer: ${{ secrets.CX_SERVER }}
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: ${{ secrets.CX_TEAM }}
        cxVersion: "2020.2.11"
        cxLog: log.log
        cxGithubIssues: true
        cxGithubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
