name: 2020.2.11 OSA Scan
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: OsaScan
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: ${{ secrets.CX_TEAM }}
        cxOsaPathExclude: "**/*cxcli*,**/*coverage,**/*images,**/*.vscode,**/*tests,**/*.git,**/*.github"
        cxOsaFilesExclude: "**/*action.yml,**/*LICENSE,**/*.md,**/*.gitignore"
        cxOsaHigh: 0
        cxOsaMedium: 0
        cxLog: log.log
        cxSkipIfFail: true
        cxVersion: "2020.2.7"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
