name: 2020.2.11 Revoke Token Trust Certs True
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: RevokeToken
        cxToken: ${{ secrets.CX_TOKEN }}
        cxTrustedCertificates: true
        cxVersion: "2020.2.11"
