name: Checkmarx SAST Scan

on:
  push:
    branches: 
      - master
jobs:
  checkmarx-scan:
    name: Run Checkmarx Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Checkmarx SAST Scan
      id: checkmarx
      uses: ./      
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxUsername: Miguel.Freitas@checkmarx.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer\SP\EMEA\__psteam
