name: Checkmarx Generate Token 8.7
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxAction: GenerateToken
        cxUsername: Miguel.Freitas@checkmarx.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxVersion: "8.7"
