name: Checkmarx Generate Token Log
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: GenerateToken
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxLog: log.log
        cxSkipIfFail: true
