name: Checkmarx OSA Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxAction: OsaScan
        cxUsername: Miguel.Freitas@checkmarx.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer\SP\EMEA\__psteam
        cxOsaPathExclude: ".github,coverage,images,.vscode,cxcli,tests"
        cxOsaHigh: 0
        cxOsaMedium: 0
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
