name: Checkmarx Revoke Token Wrong Token
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: RevokeToken
        cxToken: "123456"
        cxSkipIfFail: true
