name: Checkmarx Revoke Token 8.7
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: RevokeToken
        cxToken: ${{ secrets.CX_TOKEN }}
        cxVersion: "8.7"
