name: Checkmarx Revoke Token False Verbose
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxAction: RevokeToken
        cxToken: ${{ secrets.CX_TOKEN }}
        cxLog: log.log
