name: Checkmarx SAST Scan - Base
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxUsername: Miguel.Freitas@checkmarx.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer\SP\EMEA\__psteam
